// <auto-generated />
namespace SquareSoft.Blue.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class GetPastWeekSales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetPastWeekSales));
        
        string IMigrationMetadata.Id
        {
            get { return "201810150741244_GetPastWeekSales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
