// <auto-generated />
namespace SquareSoft.Blue.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class GetExpProd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetExpProd));
        
        string IMigrationMetadata.Id
        {
            get { return "201810150800181_GetExpProd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
